[project]
name = "playlistinator"
version = "0.1.0"
description = ""
authors = [
    {name = "MagicG5509",email = "106779600+Anonamous13243@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]

[tool.poetry]
packages = [{include = "playlistinator", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
